spring:
  datasource:
    # driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://10.10.220.154:3306/puhui_settlement?useUnicode=true&amp;characterEncoding=utf-8
    # username: root
    # password: PuhuiTest001
    type: com.zaxxer.hikari.HikariDataSource
    continue-on-error: false
    jmx-enabled: true


    hikari:
      pool-name: Cockpit-Pool
      maximum-pool-size: 30
      allow-pool-suspension: true
      login-timeout: 100
      max-lifetime: 120

      connection-init-sql: SELECT x'417574686F723A204173696E204C6975'
      connection-test-query: SELECT 1
      connection-timeout: 5000
      validation-timeout: 3000

      minimum-idle: 1
      idle-timeout: 120
      auto-commit: false
      initializationFailTimeout: 200
      register-mbeans: false
      leak-detection-threshold: 80
  aop:
    proxy-target-class: true

mybatis:
  # check-config-location: true
  # config-location: classpath*:**/mappers/*.xml
  # type-handlers-package:
  executor-type: simple
  type-aliases-package: com.github.cockpit.domain
  # mapper-locations: classpath*:**/mappers/*.xml
  configuration:
    cache-enabled: true


