DROP TABLE IF EXISTS test_usr;
DROP TABLE IF EXISTS test_fr;
CREATE TABLE IF NOT EXISTS test_usr(
  id BIGINT AUTO_INCREMENT PRIMARY KEY ,
  account VARCHAR(32) NOT NULL COMMENT '',
  phone VARCHAR(16) NOT NULL COMMENT '',
  password VARCHAR(32) NOT NULL COMMENT ''
);

CREATE TABLE IF NOT EXISTS test_fr(
  id BIGINT AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(32) NOT NULL COMMENT ''

);
